/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scical;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class CalInterface extends javax.swing.JFrame {

    /**
     * Creates new form CalInterface
     */
    int xMouse;
    int yMouse;
    static int p,m,mul,div,rt,pw,per,sn,cs,tn,ct,sc,cc;
    public CalInterface() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        result_view = new javax.swing.JTextField();
        button2 = new javax.swing.JButton();
        button_plus = new javax.swing.JButton();
        button_pow = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        button_point = new javax.swing.JButton();
        button_minus = new javax.swing.JButton();
        button_mul = new javax.swing.JButton();
        button_div = new javax.swing.JButton();
        button_equal = new javax.swing.JButton();
        button_per = new javax.swing.JButton();
        button_ace = new javax.swing.JButton();
        button_del = new javax.swing.JButton();
        button_root = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        cot = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        sec = new javax.swing.JButton();
        cosec = new javax.swing.JButton();
        expo = new javax.swing.JButton();
        log = new javax.swing.JButton();
        prime = new javax.swing.JButton();
        qroot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        titlebar = new javax.swing.JPanel();
        hide = new javax.swing.JLabel();
        cross = new javax.swing.JLabel();
        hide1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        result_view.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 24)); // NOI18N
        result_view.setText("0");
        result_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_viewActionPerformed(evt);
            }
        });
        jPanel1.add(result_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 667, 59));

        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 50, 50));

        button_plus.setText("+");
        button_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_plusActionPerformed(evt);
            }
        });
        jPanel1.add(button_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 50, 40));

        button_pow.setText("pow");
        button_pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_powActionPerformed(evt);
            }
        });
        jPanel1.add(button_pow, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 70, 40));

        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 50, 50));

        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 50, 50));

        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 50, 50));

        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 50, 50));

        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 50, 50));

        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel1.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 50, 50));

        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 50, 50));

        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        jPanel1.add(button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 50, 50));

        button_point.setText(".");
        button_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pointActionPerformed(evt);
            }
        });
        jPanel1.add(button_point, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 50, 50));

        button_minus.setText("-");
        button_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_minusActionPerformed(evt);
            }
        });
        jPanel1.add(button_minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 50, 40));

        button_mul.setText("*");
        button_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mulActionPerformed(evt);
            }
        });
        jPanel1.add(button_mul, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 50, 40));

        button_div.setText("/");
        button_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_divActionPerformed(evt);
            }
        });
        jPanel1.add(button_div, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 60, 50));

        button_equal.setText("=");
        button_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_equalActionPerformed(evt);
            }
        });
        jPanel1.add(button_equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 50, 50));

        button_per.setText("%");
        button_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_perActionPerformed(evt);
            }
        });
        jPanel1.add(button_per, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 70, 40));

        button_ace.setText("Ace");
        button_ace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_aceActionPerformed(evt);
            }
        });
        jPanel1.add(button_ace, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 70, 40));

        button_del.setText("Del");
        button_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_delActionPerformed(evt);
            }
        });
        jPanel1.add(button_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 70, 40));

        button_root.setText("Root");
        button_root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_rootActionPerformed(evt);
            }
        });
        jPanel1.add(button_root, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 70, 40));

        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 50, 50));

        cot.setText("cot");
        cot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotActionPerformed(evt);
            }
        });
        jPanel1.add(cot, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 80, -1));

        cos.setText("Cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        jPanel1.add(cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 80, -1));

        sin.setText("Sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        jPanel1.add(sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 80, -1));

        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        jPanel1.add(tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 80, -1));

        sec.setText("sec");
        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });
        jPanel1.add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 80, -1));

        cosec.setText("Cosec");
        cosec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosecActionPerformed(evt);
            }
        });
        jPanel1.add(cosec, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 80, -1));

        expo.setText("Exp");
        expo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expoActionPerformed(evt);
            }
        });
        jPanel1.add(expo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 80, -1));

        log.setText("Log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        jPanel1.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 80, -1));

        prime.setText("prime");
        prime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeActionPerformed(evt);
            }
        });
        jPanel1.add(prime, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        qroot.setText("qroot");
        qroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrootActionPerformed(evt);
            }
        });
        jPanel1.add(qroot, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CYBERSPACE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 100, -1));

        titlebar.setBackground(new java.awt.Color(153, 153, 153));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });
        titlebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scical/images/icons8_Subtract_28px_1.png"))); // NOI18N
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        titlebar.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 40, 30));

        cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scical/images/icons8_Delete_20px_2.png"))); // NOI18N
        cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossMouseClicked(evt);
            }
        });
        titlebar.add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 40, 30));

        hide1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide1MouseClicked(evt);
            }
        });
        titlebar.add(hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 30, 20));

        jPanel1.add(titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void result_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_result_viewActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="1";
            result_view.setText(text);
        }
        else
        {
           result_view.setText("1");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button_aceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_aceActionPerformed
        // TODO add your handling code here:
        result_view.setText("0");
        valp=0;
    }//GEN-LAST:event_button_aceActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="2";
            result_view.setText(text);
        }
        else
        {
           result_view.setText("2");
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="3";
            result_view.setText(text);
        }
        else
        {
           result_view.setText("3");
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="4";
            result_view.setText(text);
        }
        else
        {
           result_view.setText("4");
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="5";
            result_view.setText(text);
        }
        else
        {
           result_view.setText("5");
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="6";
            result_view.setText(text);
        }
        else
        {
           result_view.setText("6");
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="7";
            result_view.setText(text);
        }
        else
        {
           result_view.setText("7");
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="8";
            result_view.setText(text);
        }
        else
        {
           result_view.setText("8");
        }
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="9";
            result_view.setText(text);
        }
        else
        {
           result_view.setText("9");
        }
    }//GEN-LAST:event_button9ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        if(!("0").equals(text))
        {
            text+="0";
            result_view.setText(text);
        }
        
    }//GEN-LAST:event_button0ActionPerformed
    
    private void button_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pointActionPerformed
        // TODO add your handling code here:
       
         String text = result_view.getText();
         boolean check = text.contains(".");
         if(!check )
         {
            text+=".";
            result_view.setText(text);
         }
        
    }//GEN-LAST:event_button_pointActionPerformed
    double valp;
    private void button_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_plusActionPerformed
        // TODO add your handling code here:
        if(p==1)
        {
            String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            valp = valp+val2;
            result_view.setText("0");
        }
        else
        {
        p=1;
        String text = result_view.getText();
        valp = Double.parseDouble(text);
        result_view.setText("0");
        }
    }//GEN-LAST:event_button_plusActionPerformed

    private void button_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_equalActionPerformed
        // TODO add your handling code here:
        if(p==1)
        {
            String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            result_view.setText(Double.toString(valp+val2));
            p=0;
        }
        else if(m==1)
        {
            String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            result_view.setText(Double.toString(valp-val2));
            m=0;
        }
        else if(mul==1)
        {
            String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            result_view.setText(Double.toString(valp*val2));
            mul=0;
        }
        else if(div==1)
        {
                String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            if(val2!=0)
            {
            result_view.setText(Double.toString(valp/val2));
            mul=0;
            
            }
            else
            {
                result_view.setText("0");
                JOptionPane.showMessageDialog(null, "Diveded by zero");
                valp=0;
            }
            
        }
        else if(pw==1)
        {
             String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            result_view.setText(Double.toString(Math.pow(valp, val2)));
            pw=0;
        }
        else if(per==1)
        {
             String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            result_view.setText(Double.toString((valp*val2)/100.00));
            per=0;
        }
    }//GEN-LAST:event_button_equalActionPerformed

    private void button_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_minusActionPerformed
        // TODO add your handling code here:
        if(m==1)
        {
            String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            valp = valp-val2;
            result_view.setText("0");
        }
        else
        {
        m=1;
        String text = result_view.getText();
        valp = Double.parseDouble(text);
        result_view.setText("0");
        }
    }//GEN-LAST:event_button_minusActionPerformed

    private void button_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mulActionPerformed
        // TODO add your handling code here:
         if(mul==1)
        {
            String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            valp = valp*val2;
            result_view.setText("0");
        }
        else
        {
        mul=1;
        String text = result_view.getText();
        valp = Double.parseDouble(text);
        result_view.setText("0");
        }
    }//GEN-LAST:event_button_mulActionPerformed

    private void button_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_divActionPerformed
        // TODO add your handling code here:
          if(div==1)
        {
            String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            if(val2!=0)
            {
            valp = valp/val2;
            result_view.setText("0");
            
            }
            else
            {
                result_view.setText(Double.toString(valp));
                JOptionPane.showMessageDialog(null, "Diveded by zero");
            }
        
        }
        else
        {
        div=1;
        String text = result_view.getText();
        valp = Double.parseDouble(text);
        result_view.setText("0");
        }
    }//GEN-LAST:event_button_divActionPerformed

    private void button_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delActionPerformed
        // TODO add your handling code here:
        String text = result_view.getText();
       // int len=text.trim
        
    }//GEN-LAST:event_button_delActionPerformed

    private void button_rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_rootActionPerformed
        // TODO add your handling code here:
        String text = result_view.getText();
        double valp = Double.parseDouble(text);
        result_view.setText(Double.toString(Math.sqrt(valp)));
    }//GEN-LAST:event_button_rootActionPerformed

    private void button_powActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_powActionPerformed
        // TODO add your handling code here:
        if(pw==1)
        {
            String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            valp = Math.pow(valp, val2);
            result_view.setText("0");
        }
        else
        {
        pw=1;
        String text = result_view.getText();
        valp = Double.parseDouble(text);
        result_view.setText("0");
        }
    }//GEN-LAST:event_button_powActionPerformed

    private void button_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_perActionPerformed
        // TODO add your handling code here:
         if(per==1)
        {
            String text = result_view.getText();
            double val2 = Double.parseDouble(text);
            valp = (valp*val2)/100.00;
            result_view.setText("0");
        }
        else
        {
        per=1;
        String text = result_view.getText();
        valp = Double.parseDouble(text);
        result_view.setText("0");
        }
    }//GEN-LAST:event_button_perActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
        
       String text = result_view.getText();
       double valp=Double.parseDouble(text);
       result_view.setText(Double.toString(Math.sin(valp)));
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
       double valp=Double.parseDouble(text);
       result_view.setText(Double.toString(Math.cos(valp)));
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
       double valp=Double.parseDouble(text);
       result_view.setText(Double.toString(Math.tan(valp)));
    }//GEN-LAST:event_tanActionPerformed

    private void cotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
       double valp=Double.parseDouble(text);
       result_view.setText(Double.toString(1/(Math.tan(valp))));
    }//GEN-LAST:event_cotActionPerformed

    private void cosecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosecActionPerformed
        // TODO add your handling code here:
        String text = result_view.getText();
       double valp=Double.parseDouble(text);
       result_view.setText(Double.toString(1/(Math.sin(valp))));
    }//GEN-LAST:event_cosecActionPerformed

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
        String text = result_view.getText();
       double valp=Double.parseDouble(text);
       result_view.setText(Double.toString(1/(Math.cos(valp))));
     
    }//GEN-LAST:event_secActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
       double valp=Double.parseDouble(text);
       result_view.setText(Double.toString(Math.log(valp)));
    }//GEN-LAST:event_logActionPerformed

    private void expoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expoActionPerformed
        // TODO add your handling code here:
        String text = result_view.getText();
       double valp=Double.parseDouble(text);
       result_view.setText(Double.toString(Math.exp(valp)));
    }//GEN-LAST:event_expoActionPerformed

    private void primeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeActionPerformed
        // TODO add your handling code here:
        String text = result_view.getText();
        boolean check = text.contains(".");
        if(check)
        {
            JOptionPane.showMessageDialog(null, "Not Prime");
            result_view.setText("0");
        }
        else
        {
            int c=0;
            int vall = Integer.parseInt(text);
            if(vall==2)
            {
                JOptionPane.showMessageDialog(null, "Number is Prime");
                 result_view.setText("0");
            }
            else if(vall%2==0)
            {
                 JOptionPane.showMessageDialog(null, "Number is not Prime");
                 result_view.setText("0");
            }
            else
            {
                for(int i=3;i*i<vall;i=i+2)
                {
                    if(vall%i==0)
                    {
                        c++;
                        break;
                    }
                }
                if(c==0)
                {
                      JOptionPane.showMessageDialog(null, "Number is Prime");
                 result_view.setText("0");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Number is not Prime");
                 result_view.setText("0");
                }
               
                }
        }
    }//GEN-LAST:event_primeActionPerformed

    private void qrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrootActionPerformed
        // TODO add your handling code here:
         String text = result_view.getText();
        double valp = Double.parseDouble(text);
        result_view.setText(Double.toString(Math.cbrt(valp)));
    }//GEN-LAST:event_qrootActionPerformed

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        // TODO add your handling code here:
        //    JFrame.setState(Frame.ICONIFIED);
        //   JFrame jf = new JFrame();
        //jf.setState(JFrame.ICONIFIED);
        //    jf.dispatchEvent(new WindowEvent(jf, WindowEvent.WINDOW_ICONIFIED));
     //   this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_hideMouseClicked

    private void crossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_crossMouseClicked

    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_titlebarMouseDragged

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titlebarMousePressed

    private void hide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MouseClicked
        // TODO add your handling code here:
        //    JFrame.setState(Frame.ICONIFIED);
        //   JFrame jf = new JFrame();
        //jf.setState(JFrame.ICONIFIED);
        //    jf.dispatchEvent(new WindowEvent(jf, WindowEvent.WINDOW_ICONIFIED));
  //      this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_hide1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton button_ace;
    private javax.swing.JButton button_del;
    private javax.swing.JButton button_div;
    private javax.swing.JButton button_equal;
    private javax.swing.JButton button_minus;
    private javax.swing.JButton button_mul;
    private javax.swing.JButton button_per;
    private javax.swing.JButton button_plus;
    private javax.swing.JButton button_point;
    private javax.swing.JButton button_pow;
    private javax.swing.JButton button_root;
    private javax.swing.JButton cos;
    private javax.swing.JButton cosec;
    private javax.swing.JButton cot;
    private javax.swing.JLabel cross;
    private javax.swing.JButton expo;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel hide1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton log;
    private javax.swing.JButton prime;
    private javax.swing.JButton qroot;
    private javax.swing.JTextField result_view;
    private javax.swing.JButton sec;
    private javax.swing.JButton sin;
    private javax.swing.JButton tan;
    private javax.swing.JPanel titlebar;
    // End of variables declaration//GEN-END:variables
}
